use std::collections::HashSet;

use tree_sitter::Node;

use super::{field_name_text, is_valid_ident, make_def, DefKind, Definition};

pub fn builtins() -> HashSet<&'static str> {
    [
        // constants
        "true",
        "false",
        "null",
        "TRUE",
        "FALSE",
        "NULL",
        "PHP_EOL",
        "PHP_INT_MAX",
        "PHP_INT_MIN",
        "PHP_INT_SIZE",
        "PHP_FLOAT_MAX",
        "PHP_FLOAT_MIN",
        "PHP_FLOAT_EPSILON",
        "PHP_VERSION",
        "PHP_MAJOR_VERSION",
        "PHP_MINOR_VERSION",
        "PHP_OS",
        "PHP_SAPI",
        "PHP_BINARY",
        "PHP_PREFIX",
        "E_ERROR",
        "E_WARNING",
        "E_PARSE",
        "E_NOTICE",
        "E_ALL",
        "E_STRICT",
        "E_DEPRECATED",
        "STDIN",
        "STDOUT",
        "STDERR",
        "SORT_ASC",
        "SORT_DESC",
        "SORT_REGULAR",
        "SORT_NUMERIC",
        "SORT_STRING",
        "SORT_NATURAL",
        "SORT_FLAG_CASE",
        "ARRAY_FILTER_USE_KEY",
        "ARRAY_FILTER_USE_BOTH",
        "CASE_LOWER",
        "CASE_UPPER",
        "COUNT_NORMAL",
        "COUNT_RECURSIVE",
        "ENT_QUOTES",
        "ENT_HTML5",
        "ENT_COMPAT",
        "ENT_NOQUOTES",
        "JSON_PRETTY_PRINT",
        "JSON_UNESCAPED_UNICODE",
        "JSON_UNESCAPED_SLASHES",
        "PREG_PATTERN_ORDER",
        "PREG_SET_ORDER",
        "PREG_OFFSET_CAPTURE",
        "PREG_SPLIT_NO_EMPTY",
        "PREG_SPLIT_DELIM_CAPTURE",
        "STR_PAD_LEFT",
        "STR_PAD_RIGHT",
        "STR_PAD_BOTH",
        // output
        "echo",
        "print",
        "printf",
        "sprintf",
        "fprintf",
        "vprintf",
        "var_dump",
        "print_r",
        "var_export",
        "debug_zval_dump",
        // string
        "strlen",
        "strpos",
        "strrpos",
        "stripos",
        "strripos",
        "substr",
        "substr_count",
        "substr_replace",
        "str_replace",
        "str_ireplace",
        "str_split",
        "str_word_count",
        "str_pad",
        "str_repeat",
        "str_rot13",
        "str_shuffle",
        "strrev",
        "strtolower",
        "strtoupper",
        "ucfirst",
        "lcfirst",
        "ucwords",
        "trim",
        "ltrim",
        "rtrim",
        "chop",
        "nl2br",
        "wordwrap",
        "htmlspecialchars",
        "htmlentities",
        "html_entity_decode",
        "strip_tags",
        "addslashes",
        "stripslashes",
        "quotemeta",
        "md5",
        "sha1",
        "crc32",
        "crypt",
        "password_hash",
        "password_verify",
        "explode",
        "implode",
        "join",
        "split",
        "chunk_split",
        "number_format",
        "money_format",
        "chr",
        "ord",
        "hex2bin",
        "bin2hex",
        "base64_encode",
        "base64_decode",
        "url_encode",
        "urldecode",
        "rawurlencode",
        "rawurldecode",
        "parse_str",
        "http_build_query",
        "sprintf",
        "vsprintf",
        "sscanf",
        "fscanf",
        // array
        "array",
        "list",
        "count",
        "sizeof",
        "in_array",
        "array_search",
        "array_key_exists",
        "array_keys",
        "array_values",
        "array_merge",
        "array_merge_recursive",
        "array_combine",
        "array_slice",
        "array_splice",
        "array_chunk",
        "array_flip",
        "array_reverse",
        "array_unique",
        "array_filter",
        "array_map",
        "array_walk",
        "array_walk_recursive",
        "array_reduce",
        "array_push",
        "array_pop",
        "array_shift",
        "array_unshift",
        "array_rand",
        "array_sum",
        "array_product",
        "array_diff",
        "array_intersect",
        "array_udiff",
        "array_uintersect",
        "sort",
        "rsort",
        "asort",
        "arsort",
        "ksort",
        "krsort",
        "usort",
        "uasort",
        "uksort",
        "natsort",
        "natcasesort",
        "shuffle",
        "array_multisort",
        "extract",
        "compact",
        "range",
        "array_fill",
        "array_fill_keys",
        "array_pad",
        // math
        "abs",
        "ceil",
        "floor",
        "round",
        "max",
        "min",
        "pow",
        "sqrt",
        "exp",
        "log",
        "log10",
        "fmod",
        "intdiv",
        "rand",
        "mt_rand",
        "random_int",
        "random_bytes",
        "is_nan",
        "is_infinite",
        "is_finite",
        "pi",
        "deg2rad",
        "rad2deg",
        "sin",
        "cos",
        "tan",
        "asin",
        "acos",
        "atan",
        "atan2",
        "sinh",
        "cosh",
        "tanh",
        "hypot",
        // type
        "is_array",
        "is_bool",
        "is_callable",
        "is_countable",
        "is_double",
        "is_float",
        "is_int",
        "is_integer",
        "is_long",
        "is_null",
        "is_numeric",
        "is_object",
        "is_real",
        "is_resource",
        "is_scalar",
        "is_string",
        "isset",
        "unset",
        "empty",
        "gettype",
        "settype",
        "intval",
        "floatval",
        "doubleval",
        "strval",
        "boolval",
        "serialize",
        "unserialize",
        "json_encode",
        "json_decode",
        "get_class",
        "get_parent_class",
        "method_exists",
        "property_exists",
        "class_exists",
        "interface_exists",
        "trait_exists",
        "function_exists",
        "is_a",
        "is_subclass_of",
        "instanceof",
        // file
        "fopen",
        "fclose",
        "fread",
        "fwrite",
        "fgets",
        "fgetcsv",
        "fputcsv",
        "file_get_contents",
        "file_put_contents",
        "file",
        "file_exists",
        "is_file",
        "is_dir",
        "is_readable",
        "is_writable",
        "is_executable",
        "filesize",
        "filemtime",
        "filectime",
        "fileatime",
        "unlink",
        "rename",
        "copy",
        "mkdir",
        "rmdir",
        "glob",
        "scandir",
        "realpath",
        "basename",
        "dirname",
        "pathinfo",
        "tempnam",
        "tmpfile",
        "fseek",
        "ftell",
        "rewind",
        "feof",
        "fflush",
        "flock",
        "fpassthru",
        "readfile",
        "include",
        "include_once",
        "require",
        "require_once",
        // misc
        "date",
        "time",
        "mktime",
        "strtotime",
        "strftime",
        "gmdate",
        "microtime",
        "gettimeofday",
        "checkdate",
        "date_default_timezone_set",
        "header",
        "headers_sent",
        "setcookie",
        "session_start",
        "session_destroy",
        "session_id",
        "session_name",
        "die",
        "exit",
        "eval",
        "assert",
        "trigger_error",
        "error_reporting",
        "ini_get",
        "ini_set",
        "phpversion",
        "phpinfo",
        "extension_loaded",
        "function_exists",
        "class_exists",
        "defined",
        "define",
        "constant",
        "call_user_func",
        "call_user_func_array",
        "func_get_args",
        "func_get_arg",
        "func_num_args",
        "register_shutdown_function",
        "set_error_handler",
        "set_exception_handler",
        "restore_error_handler",
        "debug_backtrace",
        "debug_print_backtrace",
        "memory_get_usage",
        "memory_get_peak_usage",
        "gc_collect_cycles",
        "gc_enable",
        "spl_autoload_register",
        "class_alias",
        // superglobals
        "_GET",
        "_POST",
        "_REQUEST",
        "_SESSION",
        "_COOKIE",
        "_SERVER",
        "_FILES",
        "_ENV",
        "GLOBALS",
        "this",
    ]
    .into_iter()
    .collect()
}

pub fn extract_definition(
    node: &Node,
    source: &str,
    kind: &str,
    depth: usize,
) -> Option<Definition> {
    match kind {
        "function_definition" => {
            let (name, s, e) = field_name_text(node, source, "name")?;
            Some(make_def(name, DefKind::Function, s, e, depth))
        }
        "class_declaration" => {
            let (name, s, e) = field_name_text(node, source, "name")?;
            Some(make_def(name, DefKind::Class, s, e, depth))
        }
        "interface_declaration" => {
            let (name, s, e) = field_name_text(node, source, "name")?;
            Some(make_def(name, DefKind::Type, s, e, depth))
        }
        "method_declaration" => {
            let (name, s, e) = field_name_text(node, source, "name")?;
            Some(make_def(name, DefKind::Function, s, e, depth))
        }
        "assignment_expression" => {
            let left = node.child_by_field_name("left")?;
            if left.kind() == "variable_name" {
                let text = left.utf8_text(source.as_bytes()).ok()?.trim();
                if !text.is_empty() {
                    return Some(make_def(
                        text,
                        DefKind::Variable,
                        left.start_byte() as u32,
                        left.end_byte() as u32,
                        depth,
                    ));
                }
            }
            None
        }
        "simple_parameter" | "variadic_parameter" => {
            let (name, s, e) = field_name_text(node, source, "name")?;
            Some(make_def(name, DefKind::Parameter, s, e, depth))
        }
        "property_declaration" => {
            let mut cursor = node.walk();
            for child in node.named_children(&mut cursor) {
                if child.kind() == "property_element" {
                    if let Some((name, s, e)) = field_name_text(&child, source, "name") {
                        return Some(make_def(name, DefKind::Variable, s, e, depth));
                    }
                }
            }
            None
        }
        "namespace_use_declaration" => {
            let text = node.utf8_text(source.as_bytes()).ok()?.trim();
            let simple = text
                .trim_start_matches("use")
                .trim()
                .trim_end_matches(';')
                .rsplit('\\')
                .next()
                .unwrap_or("")
                .trim();
            if !simple.is_empty() && is_valid_ident(simple) {
                return Some(make_def(
                    simple,
                    DefKind::Import,
                    node.start_byte() as u32,
                    node.end_byte() as u32,
                    depth,
                ));
            }
            None
        }
        _ => None,
    }
}
