import { app } from "electron";
import type { NativeBridge } from "../native/types";
import { registerPtyHandlers } from "../pty/registerPtyHandlers";
import { registerNativeHandlers } from "./handlers/nativeHandlers";
import { registerApiConfigHandlers } from "./handlers/apiConfigHandlers";
import { registerChatHandlers } from "./handlers/chatHandlers";
import { registerConfigHandlers } from "./handlers/configHandlers";
import { registerConversationHandlers } from "./handlers/conversationHandlers";
import { registerWorkspaceHandlers } from "./handlers/workspaceHandlers";
import { registerSshHandlers } from "./handlers/sshHandlers";
import { registerGitHandlers } from "./handlers/gitHandlers";
import { registerWindowHandlers } from "./handlers/windowHandlers";
import { registerNotificationHandlers } from "./handlers/notificationHandlers";
import { registerMemoHandlers } from "./handlers/memoHandlers";
import { registerPersonalizationHandlers } from "./handlers/personalizationHandlers";
import { registerCodexHandlers } from "./handlers/codexHandlers";
import { registerImportConfigHandlers } from "./handlers/importConfigHandlers";
import { registerImageHandlers } from "./handlers/imageHandlers";
import { registerImageLibraryHandlers } from "./handlers/imageLibraryHandlers";
import { PluginRuntimeManager } from "../plugins/pluginRuntimeManager";

export const registerIpcHandlers = (native: NativeBridge): void => {
  const pluginRuntime = new PluginRuntimeManager();
  app.once("before-quit", () => pluginRuntime.stopAll());
  registerPtyHandlers();

  registerNativeHandlers(native);
  registerApiConfigHandlers(native);
  registerChatHandlers(native);
  registerConfigHandlers(native);
  registerConversationHandlers(native);
  registerWorkspaceHandlers(native);
  registerSshHandlers(native);
  registerGitHandlers(native);
  registerWindowHandlers(native);
  registerNotificationHandlers();
  registerMemoHandlers(native);
  registerPersonalizationHandlers();
  registerCodexHandlers(native);
  registerImportConfigHandlers(native, pluginRuntime);
  registerImageHandlers(native);
  registerImageLibraryHandlers(native);
};
